apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "mongostoragevolume" 
spec:
  capacity:
    storage: "100Gi" 
  accessModes:
    - "ReadWriteMany"
  azureFile: 
    secretName: azure-secret 
    shareName: k8stest 
    readOnly: false 