apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "mongostorageclaim"
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "10Gi"
  volumeName: "mongostoragevolume"